### ISSUE TITLE
"fatal error: qt_robot_interface/behavior_talk_audio.h: No such file or directory"

### ISSUE THREAD

**Issue by datvtmkac** [luxai-qtrobot/tutorials#1]
Hi everyone,

I'm trying to build this source code in my ROS workspace but I got this error. It seems like there is no directory name "qt_robot_interface". So can you guys show me how to fix it? 
Thank you guys a lot with respect!

Rabbit.

**Comment by codionysus** [comment]
Hi,
It looks like you don't have QTrobot ROS header files. Are you working on your PC?

**Comment by Waheguru123-prog** [comment]
how and where can i find qt robot source code file actually i want to find vulnerabilities in the system using static code analysis ?
